### ISSUE TITLE
Colors configurable from file

### ISSUE THREAD

**Issue by jwilm** [jwilm/alacritty#1]
I've already added the default color scheme to the default config file. It's reproduced below. Colors specified in the config file should actually be loaded and used. That is, this configuration should have an effect.

```yml
# Colors
colors:
  # Default colors
  default:
    background: 0x000000
    foreground: 0xeaeaea

  # Normal colors
  normal:
    black: 0x000000
    red: 0xd54e53
    green: 0xb9ca4a
    yellow: 0xe6c547
    blue: 0x7aa6da
    magenta: 0xc397d8
    cyan: 0x70c0ba
    white: 0x424242

  # Bright colors
  bright:
    black: 0x666666
    red: 0xff3334
    green: 0x9ec400
    yellow: 0xe7c547
    blue: 0x7aa6da
    magenta: 0xb77ee0
    cyan: 0x54ced6
    white: 0x2a2a2a
```
