### ISSUE TITLE
Large negative horizontal offsets cause problems

### ISSUE THREAD

**Issue by shicks** [jwilm/alacritty#1052]
Which operating system does the issue occur on?
linux

If on linux, are you using X11 or Wayland?
X11

59b561b seems to have broken my alacritty.yml config.  I previously had the following:

```yaml
font:
  normal:
    family: Monofur Nerd Font
    style: Book

  bold:
    family: Monofurbold Nerd Font
    style: Bold

  italic:
    family: Monofuritalic Nerd Font
    style: Italic

  size: 11.0

  offset:
    # NOTE: We seem to need a big negative offset to counteract the fact
    # that there are double-wide glyphs in the font.  On top of that, we
    # also add a couple extra pixels to tighten things up and to eliminate
    # ugly vertical lines between powerline glyphs.
    x: -13.0
    y: 0.0
```

I wrote this config a while back, but a little experimentation reveals that, indeed, without the large negative offset, I get pretty horrible spacing between glyphs when the font is not strictly monospaced (in my case, monofur has a few double-width glyphs).  I assume the terminal was just taking the maximum width and using that for everything.  But after 59b561b there seems to be a threshold (for Monofur 11, it's -8) and when I start the terminal, I get one of three outcomes:

  * offset is less negative than the threshold: works as expected, though the offset is a lot more noticeable (probably because it's working correctly)
  * offset is exactly the threshold: terminal immediately crashes with this error:
    ```
    thread 'main' panicked at 'capacity overflow', /checkout/src/libcore/option.rs:874:4
    note: Run with `RUST_BACKTRACE=1` for a backtrace.
    ```
  * offset is more negative than the threshold: window appears but is completely blank and does not (seem to) respond to keypresses (i.e. Ctrl-D does not quit)

In my case, it was an easy fix to just stop using the weird large negative offset, but it took a lot of effort to discover that this was the culprit.  At the very least, we should detect this case and report a more useful error message.
