### ISSUE TITLE
Doesn't start if I specify Fira Mona as font family

### ISSUE THREAD

**Issue by codeinabox** [jwilm/alacritty#1053]
Which operating system does the issue occur on? OS X

I am trying to specify the font family of Fira Mono in my configuration when I do Alacritty doesn't start.

```yml
# Font configuration (changes require restart)
font:
  # The normal (roman) font face to use.
  normal:
    family: "Fira Mona"
    # Style can be specified to pick a specific face.
    # style: Regular

  # The bold font face
  bold:
    family: "Fira Mona"
    # Style can be specified to pick a specific face.
    # style: Bold

  # The italic font face
  italic:
    family: "Fira Mona"
    # Style can be specified to pick a specific face.
    # style: Italic

  # Point size of the font
  size: 12.0

```
