### ISSUE TITLE
Create a separate `cursor` field in the config

### ISSUE THREAD

**Issue by chrisduerr** [jwilm/alacritty#1080]
So after the #1079 PR had some interesting ways to name the variable it introduced, I kinda thought a bit about how I would have named it and came to the conclusion that the current cursor configuration could be simplified a bit.

### Current state

```yml
cursor_style: Block
hide_cursor_when_typing: true
custom_cursor_colors: false

colors:
    cursor:
        background: '0xffffff'
        foreground: '0xffffff'
        text: '0x1b1b1b'
        cursor: '0x9e9e9e'
```

### Proposal
```yml
cursor:
    style: Block
    hide_when_typing: false

colors:
    cursor:
        custom_colors: true
        background: '0xffffff'
        foreground: '0xffffff'
        text: '0x1b1b1b'
        cursor: '0x9e9e9e'
````

### Idea
The idea behind this new way to handle cursor settings in the alacritty yml is to make it simple to read and find the current cursor settings and allow expansion without any confusion.
By making the location and structure uniform, instead of having `cursor` at the start, middle or end, it might help users with finding the config variables they are looking for. If they are looking for a config setting and it's not in `cursor`, it probabl doesn't exist.

### Alternatives
A different solution than my proposal could be adding a `color` block inside the `cursor` block, so really everything related to `cursor` is inside of `cursor`. However then not everything related to `color` is in `color` and it might make the colorschemes in the wiki harder.
