### ISSUE TITLE
Script to convert Konsole colorscheme to Alacritty color scheme 

### ISSUE THREAD

**Issue by 22459** [jwilm/alacritty#1093]
I made a script, putting it here so that maybe it's useful for someone. (I don't know where else to put it.)
It needs python 3 and pyyaml. You run it on files like `python3 converter.py /share/konsole/Linux.colorscheme`.

```python
#Note this does not generate the 'cursor:' section becuase I don't know what would correspond to that.
#I also dont know if theres an equivalent light/dark for the foreground/background so those are ignored.
#Also alacritty does not have "dark" colors. (?)

import sys
import configparser as confp #ini format
import yaml
import collections

#fixes extraneous stuff when yaml-ing a defaultdict
from yaml.representer import Representer
yaml.add_representer(collections.defaultdict, Representer.represent_dict)

confpath = sys.argv[1]
c = confp.ConfigParser() 
c.read(confpath)

colormap = {
	'Color0':'black',
	'Color1':'red',
	'Color2':'green',
	'Color3':'yellow',
	'Color4':'blue',
	'Color5':'magenta',
	'Color6':'cyan',
	'Color7':'white',
	'Foreground':'foreground',
	'Background':'background',
	}

typemap = {
	'Intense':'bright',
	'Faint':'dark',
	'#default#':'normal'
	}

def stype(s):
	for k,v in typemap.items():
		if s.endswith(k):
			return v
	return typemap['#default#']

def ctype(sb):
	for k,v in colormap.items():
		if s.startswith(k):
			return v
	raise NotImplementedError

def hexcolor(s):
	tohex = lambda x: "{0:02x}".format(int(x))
	return "0x%s" % "".join([tohex(x) for x in s.split(",")])

data = { 'colors' : collections.defaultdict(dict) }

for s in c.sections():
	if "color" in c[s] and stype(s) is not "dark":
		if ctype(s) in ["foreground","background"]:
			if stype(s) == "normal":
				data['colors']["primary"][ctype(s)] = hexcolor(c[s]['color'])
			else:
				pass
			continue
		data['colors'][stype(s)][ctype(s)] = hexcolor(c[s]['color'])

print(yaml.dump(data, default_flow_style=False))
```

Example output is:
```yaml
colors:
  bright:
    black: '0x686868'
    blue: '0x5454ff'
    cyan: '0x54ffff'
    green: '0x54ff54'
    magenta: '0xff54ff'
    red: '0xff5454'
    white: '0xffffff'
    yellow: '0xffff54'
  normal:
    black: '0x000000'
    blue: '0x1818b2'
    cyan: '0x18b2b2'
    green: '0x18b218'
    magenta: '0xb218b2'
    red: '0xb21818'
    white: '0xb2b2b2'
    yellow: '0xb26818'
  primary:
    background: '0x000000'
    foreground: '0xb2b2b2'
```
to which you should add something like
```yaml
  cursor:
    text: '0x2E3440'
    cursor: '0xD8DEE9'
```
