### ISSUE TITLE
YAML references don't work in config file

### ISSUE THREAD

**Issue by mathroc** [jwilm/alacritty#1127]
I wanted to add switch color themes easily so I added a `themes` section :

```yaml

themes:
  # Colors (Tomorrow Night Bright)
  default: &default
    # Default colors
    primary:
      background: '0x000000'
      foreground: '0xeaeaea'

    # Colors the cursor will use if `custom_cursor_colors` is true
    cursor:
      text: '0x000000'
      cursor: '0xffffff'

    # Normal colors
    normal:
      black:   '0x000000'
      red:     '0xd54e53'
      green:   '0xb9ca4a'
      yellow:  '0xe6c547'
      blue:    '0x7aa6da'
      magenta: '0xc397d8'
      cyan:    '0x70c0ba'
      white:   '0xffffff'

    # Bright colors
    bright:
      black:   '0x666666'
      red:     '0xff3334'
      green:   '0x9ec400'
      yellow:  '0xe7c547'
      blue:    '0x7aa6da'
      magenta: '0xb77ee0'
      cyan:    '0x54ced6'
      white:   '0xffffff'

    # Dim colors (Optional)
    dim:
      black:   '0x333333'
      red:     '0xf2777a'
      green:   '0x99cc99'
      yellow:  '0xffcc66'
      blue:    '0x6699cc'
      magenta: '0xcc99cc'
      cyan:    '0x66cccc'
      white:   '0xdddddd'

  solarized: &solarized
  # Colors (Solarized Dark)
    # Default colors
    primary:
      background: '0x002b36'
      foreground: '0x839496'

    # Normal colors
    normal:
      black:   '0x073642'
      red:     '0xdc322f'
      green:   '0x859900'
      yellow:  '0xb58900'
      blue:    '0x268bd2'
      magenta: '0xd33682'
      cyan:    '0x2aa198'
      white:   '0xeee8d5'

    # Bright colors
    bright:
      black:   '0x002b36'
      red:     '0xcb4b16'
      green:   '0x586e75'
      yellow:  '0x657b83'
      blue:    '0x839496'
      magenta: '0x6c71c4'
      cyan:    '0x93a1a1'
      white:   '0xfdf6e3'
  # Colors (Oceanic Next)
  oceanic:
    # Default colors
    primary:
      background: '0x1b2b34'
      foreground: '0xD8DEE9'

    # Colors the cursor will use if `custom_cursor_colors` is true
    cursor:
      text: '0xec5f67'
      cursor: '0xec5f67'

    # Normal colors
    normal:
      black:   '0x343d46'
      red:     '0xEC5f67'
      green:   '0x99C794'
      yellow:  '0xFAC863'
      blue:    '0x6699cc'
      magenta: '0xc594c5'
      cyan:    '0x5fb3b3'
      white:   '0xd8dee9'

    # Bright colors
    bright:
      black:   '0x343d46'
      red:     '0xEC5f67'
      green:   '0x99C794'
      yellow:  '0xFAC863'
      blue:    '0x6699cc'
      magenta: '0xc594c5'
      cyan:    '0x5fb3b3'
      white:   '0xd8dee9'
```

and then I wanted to select the theme like that:

```yaml
colors:
  <<: *solarized
```

is that something that could be supported ?

about YAML anchors & references: http://blog.daemonl.com/2016/02/yaml.html

**Comment by jwilm** [comment]
This appears to be [a bug](https://github.com/chyh1990/yaml-rust/issues/68) in Rust's YAML parser. Alacritty can support it once the parser does, but it doesn't appear to be actively worked on.

**Comment by nuclearsandwich** [comment]
I was pointed to this issue in the `#alacritty` channel on Freenode.

I'm able to use [this config file](https://gist.github.com/nuclearsandwich/a6ac67543601ad642cee635aec079f41#file-alacritty-yml-L121) to swap colors configuration by updating the reference using alacritty 0.1.0 (an old version I had lying around from source) and 0.2.1 from the Archlinux repositories.

It looks like switching colors works as long as you're directly referencing the anchor but the extend syntax `<<:` doesn't work.

**Comment by nuclearsandwich** [comment]
@mathroc do you think a block a the start or end of the https://github.com/jwilm/alacritty/wiki/Color-schemes page is where this belongs or should I create a standalone page and just link it.

**Comment by mathroc** [comment]
it might not be for me to say, but in the same page seems enough. 

the default config file could even be updated to something similar to:

```yaml
themes:
  default: &default
    primary:
      background: '0x000000'
      foreground: '0xeaeaea'

colors: *default
```

then [the Color-schemes page](https://github.com/jwilm/alacritty/wiki/Color-schemes) would only have to explain how to define a new themes and switch between them
