### ISSUE TITLE
Scroll multiplier should be configurable

### ISSUE THREAD

**Issue by maximbaz** [jwilm/alacritty#1160]
#1147 scrolls by 3 lines, which feels less smooth comparing to #657 where scroll doesn't skip any lines.

I believe it's a matter of making this constant configurable via alacritty.yml:

https://github.com/jwilm/alacritty/blob/ec49105203934a342d4aa416029ebdbbdeb1cce9/src/input.rs#L37

**Comment by chrisduerr** [comment]
Maybe we could have a separate field for scrollback, something like this:
```yml
scrollback:
    lines: 10_000 # Number of lines
    step: 3 # Lines per "scroll"
```

Alternatively we could keep the number of lines in the global config and add `scroll_multiplier` (or `scroll_step` or something like that) to the mouse section next to `faux_scrollback_lines`.
