### ISSUE TITLE
Allow TOML configuration files

### ISSUE THREAD

**Issue by clarcharr** [jwilm/alacritty#1217]
I personally prefer using TOML to YAML, and at least allowing an alacritty.toml instead of alacritty.yml would be nice.

**Comment by chrisduerr** [comment]
What advantages are you looking for? I don't see a reason to support multiple different configuration formats, it would just bloat the codebase without any advantages to the user.

**Comment by clarcharr** [comment]
I mean, presuming that the config is done through serde, it's really just a matter of doing `serde_yaml::read` versus `toml::read`. IMHO the config is simple enough that all of the nuances of a format like YAML don't really make sense, and especially given the precedent of using TOML for rust projects it seems like a good idea to just switch to TOML overall. But, given that people are already using alacritty with a YAML config, it makes sense to support both in the meantime.

**Comment by NickeZ** [comment]
Imo toml is not as good as yaml when it comes to more complex configuration. For example nested tables doesn't really scale.

**Comment by clarcharr** [comment]
I would hardly call alacritty's configuration complex.

**Comment by NickeZ** [comment]
Maybe not complex, but it uses nesting a lot which i think will look worse with toml

**Comment by clarcharr** [comment]
I'm on my phone right now but later today I'll make a TOML version of the default config. IMHO it's a lot cleaner than the YAML version.

**Comment by chrisduerr** [comment]
Yeah in my experience the nesting and arrays in toml can look a bit user-unfriendly.

The #1 goal should be that it's easy to read for the user.

**Comment by catastrop** [comment]
>Yeah in my experience the nesting and arrays in toml can look a bit user-unfriendly.

This is nonsense!

`cargo` uses toml.

**Comment by catastrop** [comment]
>Imo toml is not as good as yaml when it comes to more complex configuration. For example nested tables doesn't really scale.

so how does `cargo` handle? ......

**Comment by catastrop** [comment]
Using `yaml` in `rust` project is nonsense. `cargo` uses `toml`. So why don't you use `toml`.

**Comment by NickeZ** [comment]
@catastrop you should pick the configuration format that is best for your use case and not pick the configuration format that your programming language's build/package management system uses. Maybe you could convert the config file to toml and prove to us that it is a good fit for this use case.

It was some time since I looked into it. But I think this was approximately my reasoning. In toml nested tables look like:

```toml
[foo.bar.baz]
abc = "value"
[foo.bar.qux]
abc = "value"
```

whereas in yaml

```yaml
foo:
  bar:
    baz:
      abc: value
    quz:
      abc: value
```

arrays of tables are also horrible on toml:

```toml
[[foo]]
a = "something"
b = "something"
[[foo]]
a = "something else"
b = "something else"
```

vs

```yaml
foo:
    - a: something
      b: something
    - a: something else
      b: something else
```
