### ISSUE TITLE
Bitmap glyph not affected by offsets

### ISSUE THREAD

**Issue by Bl4ckb0ne** [jwilm/alacritty#1220]
Hi, I'm running alacritty on Archlinux with X11, and the font [ttyp0](https://people.mpi-inf.mpg.de/~uwe/misc/uw-ttyp0/). I am using the latest version available of both alacritty and ttyp0 from AUR.

I'm using the agnoster theme with fish, and the little arrow glyph is misplaced.
![](https://sr.ht/ITKh.png)
Here is the font config that i'm using
```
font:
  normal:
    family: UW ttyp0
    style: Regular

  bold:
    family: UW ttyp0 bold
    style: Bold

  italic:
    family: UW ttyp0
    style: Italic

  size: 12.0

  offset:
    x: 0.0
    y: 0.0

  glyph_offset:
    x: 0.0
    y: -2.0
```
I tried to modify the `y` offset of the glyph to something really high, and nothing moved.
