### ISSUE TITLE
add font fallback example to config template

### ISSUE THREAD

**Issue by matthiaskrgr** [jwilm/alacritty#1254]
Hi, I didn't manage to get a font fallback working.
I tried different things like
````
font:
  normal:
     family: hack
     family: monospace
````

````
font:
  normal:
     family: hack
       family: monospace
````

````
font:
  normal:
     - family: hack
     - family: monospace
````

but none appeared to work.
Could we have a working fallback example in the config template?

I use alacritty from the scrollback branch.
