### ISSUE TITLE
Using "Hack Regular" monospace font results in uneven output

### ISSUE THREAD

**Issue by towc** [jwilm/alacritty#1256]
Which operating system does the issue occur on?
ubuntu 16.04

If on linux, are you using X11 or Wayland?
X11

Here's a photo of the ouput:
![image](https://user-images.githubusercontent.com/6382186/39007018-15f7036c-4405-11e8-9bd9-ad7a98a2b240.png)

And the relevant config:
```yml
font:
  # The normal (roman) font face to use.
  normal:
    family: 'Hack Regular' # should be "Menlo" or something on macOS.
    # Style can be specified to pick a specific face.
    # style: Regular
  # The bold font face
  bold:
    family: 'Hack Regular' # should be "Menlo" or something on macOS.
    # Style can be specified to pick a specific face.
    # style: Bold
  # The italic font face
  italic:
    family: 'Hack Regular' # should be "Menlo" or something on macOS.
    # Style can be specified to pick a specific face.
    # style: Italic
  # Point size of the font
  size: 9.0
  # Offset is the extra space around each character. offset.y can be thought of
  # as modifying the linespacing, and offset.x as modifying the letter spacing.
  offset:
    x: 0
    y: 0
  # Glyph offset determines the locations of the glyphs within their cells with
  # the default being at the bottom. Increase the x offset to move the glyph to
  # the right, increase the y offset to move the glyph upward.
  glyph_offset:
    x: 0
    y: 0
  # OS X only: use thin stroke font rendering. Thin strokes are suitable
  # for retina displays, but for non-retina you probably want this set to
  # false.
  use_thin_strokes: true
```

Any clue what's wrong and what should I fix? Is an issue a good place to ask about this?
