### ISSUE TITLE
Alacritty Can't load user fonts on MacOS

### ISSUE THREAD

**Issue by Thermatix** [jwilm/alacritty#1287]
Currently running MacOS High Sierra, version 10.13.3.

The problem is that Alacritty refuses to find fonts in my `library/fonts` folder and as such won't load, all I get is:

```
Couldn't find a font with name 'Knack Regular Nerd Font Complete' and style 'Regular'
Please check the font config in your alacritty.yml.
```

font config in `~/.alacritty.yml`:
```yml
font:
  # The normal (roman) font face to use.
  normal:
    family: Knack Regular Nerd Font Complete
    # Style can be specified to pick a specific face.
    style: Regular
```

Which is a shame as I would really like to start using alacritty for it's speed as I don't need tabs as I use Tmux.

**Comment by oludiro** [comment]
@Thermatix , I was able to load the font using the font family "Knack Nerd Font".

```
font:
  # The normal (roman) font face to use.
  normal:
    family: "Knack Nerd Font"
    # Style can be specified to pick a specific face.
    style: Regular
```
