### ISSUE TITLE
Font offset.y not working

### ISSUE THREAD

**Issue by ahmedelgabri** [jwilm/alacritty#1308]
Which operating system does the issue occur on? macOS

I tried it with multiple fonts, but it doesn't work. Any idea what can be the issue or if I need to change something else in combination with it?

```yaml
font:
  normal:
    family: Iosevka Nerd Font # Tried multipe fonts
    style: Regular

  bold:
    family: Iosevka Nerd Font # Tried multipe fonts
    style: Bold

  italic:
    family: Iosevka Nerd Font # Tried multipe fonts
    style: Italic

  size: 12.0

  offset:
    x: 0.0
    y: 0.0 # I tried even 20.0, didn't work

  glyph_offset:
    x: 0.0
    y: 0.0
```
