### ISSUE TITLE
Font config doesn't seem to have an effect

### ISSUE THREAD

**Issue by martskins** [jwilm/alacritty#1474]
OS: macOS High Sierra 10.13.6

I don't know if this is a config issue or just that it doesn't support some fonts, but I can't seem to have alacritty pick some of my fonts.
The portion of my config where I'm setting my fonts looks like this:
```
font:
  normal:
    family: Fira Mono
    style: Regular
```

I have tried setting Fira Mono, Fira Code, Menlo, Hack, Monaco and they are definitely not getting set. 
Also it doesn't seem to pick up the style (at least for those fonts), I tried Light, Italic, Bold, Regular, Medium and they all look the same as well.

Some other fonts do seem to work though, I tried Zapfino and Inconsolata just to make sure and it did work.

As for the version of alacritty I'm using, I'm not quite sure, but I checkout out the latest commits in master yesterday and I'm using that build now.

Am I doing something wrong?

**Comment by chrisduerr** [comment]
The following configuration works for me on linux:
```yml
font:
  size: 10.0
  normal:
    family: Fira Mono
    style: Medium
  bold:
    family: Fira Mono
  italic:
    family: Fira Mono
```

As long as you have the font installed and specified the name correctly, Alacritty should load it properly. Please make sure your whitespace is correct though, since that is relevant. You can also launch Alacritty from a different terminal emulator to check for potential errors.
