### ISSUE TITLE
Cannot Load User Font

### ISSUE THREAD

**Issue by RcrsvSquid** [jwilm/alacritty#1493]
Which operating system does the issue occur on?
MacOS

I'm using the following config to attempt to load a nerd font to no avail. How do I translate the name of the font with nested styles from font book to the name needed in the yaml configuration?
```yaml
font:
  # The normal (roman) font face to use.
  normal:
    family: Sauce Code Pro
    # Style can be specified to pick a specific face.
```

**Comment by zhangxiubo** [comment]
Try surround the name of the font in double quotes:
```yaml
font:
  # The normal (roman) font face to use.
  normal:
    family: "Sauce Code Pro"
    # Style can be specified to pick a specific face.
```

**Comment by sodiumjoe** [comment]
I don't think the quotes are necessary, and it should just be the title in Font Book:

For example, this works for me:

```
# Font configuration (changes require restart)
font:
  # The normal (roman) font face to use.
  normal:
    family: Inconsolata Nerd Font
```

![image](https://user-images.githubusercontent.com/845857/43987861-f21a8c4e-9cdc-11e8-887b-85289acc902b.png)
