### ISSUE TITLE
How to send text on startup, run command after shell?

### ISSUE THREAD

**Issue by CodeMonkeyKevin** [jwilm/alacritty#1672]
How can I send text on startup, run command after shell?

E.g: after fish shell i want to start nvim on launch?

**Comment by nixpulvis** [comment]
Add this to your `alacritty.yml`

```
shell:
  program: /bin/bash
  args:
    - -c
    - vim
```

**Comment by chrisduerr** [comment]
@sts10 Try running `bash -c "cd ~/documents"`, that's effectively what you're doing. You'll notice that this doesn't start an interactive shell, but it starts a subshell, which changes directory and then immediately exits again.

Bash doesn't have a command line parameter to start the shell in a specific directory, but that doesn't mean it's not possible. If you try the following, you'll likely find it working:
```bash
bash -c "cd ~/documents && exec bash"
```

This creates a subshell, changes directory there and then replaces the shell with an interactive shell. Hopefully that will help.

Also this issue hasn't been updated in a long, long time and there's clearly ways to fix this problem (like the solution outlined by @nixpulvis). So closing this as resolved.

**Comment by chrisduerr** [comment]
@sts10 This should work:

```yaml
shell:
  program: /bin/zsh
  args:
    - -c
    - cd /tmp && exec zsh
```

**Comment by sts10** [comment]
Ah! Got it. Thanks so much. For posterity (and bash users):

In `~/.config/alacritty/alacritty.yml`

```yaml
# have this be the only time you set the shell path in the alacritty.yml config file
shell:
  program: /bin/bash
  args:
    - -c
    - cd ~/Documents && exec bash
```

**Comment by oschrenk** [comment]
For the `fish` users it is important to use `--init-command` instead of `--command`:

```
shell:
  program: /usr/local/bin/fish
  args:
    - --login
    - --init-command
    - "echo hello"
```

**Comment by sts10** [comment]
It'd be great to collect stuff like this in documentation of some form!

**Comment by xseman** [comment]
v 0.4.2 won't start without quotes on `args`

this config works:
```yml
shell:
  program: /usr/local/bin/fish
  args:
    - "--login"
    - "--init-command"
    - "echo hello"
````
