### ISSUE TITLE
Panic on setting Bitmap font

### ISSUE THREAD

**Issue by donniebishop** [jwilm/alacritty#185]
When setting any of the font options to use Tewi, a bitmap font, attempting to start Alacritty using rofi or dmenu causes it to briefly open before force closing.

When trying to start alacritty from another terminal, it briefly opens and force closes again. Running with backtrace enabled:

```
device_pixel_ratio: 1
width: 715, height: 217
Initializing glyph cache
num fonts = 790
num fonts = 790
num fonts = 790
thread 'main' panicked at 'index 4 out of range for slice of length 3', /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/slice.rs:560
stack backtrace:
   1:     0x562e86ed05fa - <unknown>
   2:     0x562e86ed596f - <unknown>
   3:     0x562e86ed556e - <unknown>
   4:     0x562e86ed5e17 - <unknown>
   5:     0x562e86ed5ca4 - <unknown>
   6:     0x562e86ed5bc9 - <unknown>
   7:     0x562e86ed5b57 - <unknown>
   8:     0x562e86f01c1d - <unknown>
   9:     0x562e86f01cf9 - <unknown>
  10:     0x562e86e680af - <unknown>
  11:     0x562e86df9044 - <unknown>
  12:     0x562e86df3e3e - <unknown>
  13:     0x562e86dd1037 - <unknown>
  14:     0x562e86dd09e5 - <unknown>
  15:     0x562e86edcd5a - <unknown>
  16:     0x562e86ed6556 - <unknown>
  17:     0x7f24ab0b4290 - __libc_start_main
  18:     0x562e86daa799 - <unknown>
  19:                0x0 - <unknown>

```

This is the current font configuration in `~/.config/alacritty.yml`:

```
# Font configuration (changes require restart)
font:
  # The normal (roman) font face to use.
  normal:
    family: tewi # should be "Menlo" or something on macOS.
    # Style can be specified to pick a specific face.
    # style: Regular

  # The bold font face
  bold:
    family: tewi # should be "Menlo" or something on macOS.
    # Style can be specified to pick a specific face.
    # style: Bold

  # The italic font face
  italic:
    family: tewi # should be "Menlo" or something on macOS.
    # Style can be specified to pick a specific face.
    # style: Italic

  # Point size of the font
  size: 9.0
  # Offset is the extra space around each character. offset.y can be thought of
  # as modifying the linespacing, and offset.x as modifying the letter spacing.
  offset:
    x: 2.0
    y: -7.0

```

Please let me know if there's anything else I can provide

**Comment by warptozero** [comment]
I'm getting the following with `Terminus` set as font:

```
device_pixel_ratio: 1
width: 668, height: 527
Initializing glyph cache
num fonts = 887
num fonts = 887
num fonts = 887
Finished initializing glyph cache in 0.120295312
set_inner_size: 4px × 4px
width: 4, height: 4
Cell Size: (0 x 0)
PTY Dimensions: Line(0) x Column(0)
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcollections/vec.rs:1371
stack backtrace:
   1:     0x557f66f1797a - <unknown>
   2:     0x557f66f1ccef - <unknown>
   3:     0x557f66f1c8ee - <unknown>
   4:     0x557f66f1d197 - <unknown>
   5:     0x557f66f1d024 - <unknown>
   6:     0x557f66f1cf49 - <unknown>
   7:     0x557f66f1ced7 - <unknown>
   8:     0x557f66f48f9d - <unknown>
   9:     0x557f66f48f48 - <unknown>
  10:     0x557f66e435c1 - <unknown>
  11:     0x557f66e18293 - <unknown>
  12:     0x557f66e179c5 - <unknown>
  13:     0x557f66f240da - <unknown>
  14:     0x557f66f1d8d6 - <unknown>
  15:     0x7fd0063e8290 - __libc_start_main
  16:     0x557f66df1779 - <unknown>
  17:                0x0 - <unknown>
```

**Comment by d3rrial** [comment]
Try adjusting the offsets in increments of 10 in each direction for a few times. I doubt it will help, but I've had similar crashes because my font offset was too large/small and it would be interesting to see if you can get any results.

**Comment by warptozero** [comment]
@d3rrial changing the offset didn't yield any result. However changing the font size from `10.0` to `12.0` gave a different panic:

```
device_pixel_ratio: 1
width: 668, height: 527
Initializing glyph cache
num fonts = 887
num fonts = 887
num fonts = 887
thread 'main' panicked at 'index 68 out of range for slice of length 64', /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/slice.rs:560
stack backtrace: [...]
```

Not sure whether posting any of this is helpful though.

**Comment by gyakovlev** [comment]
I'm also affected by this.

Let me know if you need any debug info.
First rust project I ever tried, will need some guidance how to provide required info.

Usually pretty happy with bitmap version of terminus.

However, there is a workaround.
I downloaded a nerdfont version of Terminus from here  http://nerdfonts.com/
and using ttf no longer crashed alacritty 

I even achieved _almost_ pixel perfect setup with the new font.
~ is a bit off, but I think it's because different version of the font.

here is a screenshot of alacritty overlayed by semi-transparent st (which is using bitmap terminus) both running cal.

![alast](https://cloud.githubusercontent.com/assets/168902/21746253/356709a4-d4f3-11e6-802c-ed3739399ada.png)

screen dpi is 227
st runs with ```static char font[] = "terminus:pixelsize=32:antialias=true:autohint=true";```

and here is some parts from yml
```
dpi:
  x: 227.0
  y: 227.0
...........
size: 10.0
  offset:
    x: 4.0
    y: 12.0
```
