### ISSUE TITLE
Ability to apply offset-y to the bottom of lines rather than the top

### ISSUE THREAD

**Issue by pikajude** [jwilm/alacritty#197]
As you can see here, my vim status bar is looking a little distressed:

![foo](https://i.imgur.com/jnsvjBO.png)

Increasing offset-y doesn't help because it adds more spacing to the *top* of the line.

**Comment by eproxus** [comment]
I think offset should be possible to set in all dimensions.

Example:
```yaml
offset:
  top: 2.0
  left: 0.0
  right: 0.0
  bottom: 4.0
```
