### ISSUE TITLE
Non-latin characters of bitmap font displayed incorrectly

### ISSUE THREAD

**Issue by hemerno** [jwilm/alacritty#2009]
#### System
OS: Arch Linux
Kernel: 4.20.1-arch1-1-ARCH
Rust version: 1.31.1
Display server: X11
Window manager: i3
Compositor: Compton
Alacritty version: 0.2.5
Example font: [Gohufont](http://font.gohu.org/)
#### Summary
Bitmap font has support for Cyrillic and Greek characters (some other glyphs are also affected), but in Alacritty those characters are displayed using the default system font and some others, depending on a character. In _libvte_-based terminals letters are displayed as intended (tested on sakura and termite). The problem persists even without a compositor.
Also found out that changing system locale in `/etc/locale.conf` (LANG variable) from en_US.UTF-8 to ru_RU.UTF-8 makes Cyrillic characters to be displayed normally, but other symbols are still distorted.
#### Expectation
![gohufont](https://user-images.githubusercontent.com/31391652/51180223-deb64300-18d8-11e9-9f68-108d61179e7e.png)
#### Screenshots
Alacritty
![2019-01-15-135542_478x510_scrot](https://user-images.githubusercontent.com/31391652/51180299-289f2900-18d9-11e9-9a64-0b5badabf5f8.png)
Termite
![2019-01-15-135539_476x510_scrot](https://user-images.githubusercontent.com/31391652/51180313-33f25480-18d9-11e9-9fae-9ffd40302380.png)
#### Config
```
font:
  normal:
    family: gohu gohufont
    style: Regular

  bold:
    family: gohu gohufont
    style: Bold

size: 14

  offset:
    x: 0
    y: 0

  glyph_offset:
    x: 0
    y: 0
```
