### ISSUE TITLE
Add proper high DPI support with X11

### ISSUE THREAD

**Issue by anderspitman** [jwilm/alacritty#202]
I'm using a 28 inch 4k display. I'm using `xrandr` to set the dpi to 168. Most applications handle the scaling fine, but some (java guis being one example) don't. Alacritty doesn't seem to. Is there a configuration for this, or if not would it be a feature I might be able to contribute (I know nothing about X programming)?

For the short term cranking up the font to 18 seems to work fairly well.

**Comment by jwilm** [comment]
I'm hoping to get support for this at some point. The windowing abstraction we use hard-codes the high-DPI scale factor to 1 for X11 :(.

For now, there's a workaround where you can configure your DPI manually in the alacritty.yml file.

**Comment by jwilm** [comment]
As far as contributing the patch to glutin to make this work out-of-the-box, it might be helpful to see what glfw does.

**Comment by anderspitman** [comment]
It looks pretty awful when I set it in alacritty.yml:
![image](https://cloud.githubusercontent.com/assets/7820200/21744214/99567aa0-d4ce-11e6-98fa-fdfdae1e14e2.png)

I'm on Arch using i3

**Comment by rrichardson** [comment]
I have a 4k display as well. 

I have set : 
```yaml
dpi: 
  x: 144.0
  y: 144.0

font:
  offset:
    x: 7.0
    y: -4.0 
```

This makes for a nice, readable screen.  If you want to run at 168 DPI,  I reckon you'll have to increase the offsets a bit more.

**Comment by anderspitman** [comment]
Ah yes it makes sense that the offsets would need to be updated as well. Thanks!

This looks pretty good for 168:

``` yml
dpi:
  x: 168.0
  y: 168.0

  offset:
    x: 8.0
    y: 3.0
```

**Comment by gyakovlev** [comment]
227 dpi screen here. here's my config.
Usually pretty happy with bitmap version of terminus in st.

I downloaded a nerdfont version of Terminus from here  http://nerdfonts.com/
Achieved _almost_ pixel perfect setup with the new font.
~ is a bit off, but I think it's because different version of the font.

here is a screenshot of alacritty overlayed by semi-transparent st (which is using bitmap terminus) both running cal.

![alast](https://cloud.githubusercontent.com/assets/168902/21746253/356709a4-d4f3-11e6-802c-ed3739399ada.png)

screen dpi is 227
st runs with ```static char font[] = "terminus:pixelsize=32:antialias=true:autohint=true";```

and here is some parts from yml
```
dpi:
  x: 227.0
  y: 227.0
...........
font:
    family: "TerminessTTF Nerd Font" # should be "Menlo" or something on macOS.
...........
size: 10.0
  offset:
    x: 4.0
    y: 12.0
```
