### ISSUE TITLE
How to disable URL launcher?

### ISSUE THREAD

**Issue by joeky888** [jwilm/alacritty#2058]
How to completely disable URL launcher?

Every time I am trying to highlight an URL and then browser shows up,

I would like to disable it.

```yaml
url:
    # URL launcher
    #
    # This program is executed when clicking on a text which is recognized as a URL.
    # The URL is always added to the command as the last parameter.
    #
    # Default:
    #   - (macOS) open
    #   - (Linux) xdg-open
    #   - (Windows) explorer
    #launcher: xdg-open
```

**Comment by chrisduerr** [comment]
It seems like this regression has been introduced when the configuration files have been merged.

It's still possible to disable URL launching by setting the `launcher` to `true`, but an option to disable this completely should be supported explicitly.

**Comment by chrisduerr** [comment]
Fixed in #2059.

**Comment by nixpulvis** [comment]
@joeky888 I'm assuming you mean that when you try to select that sometimes you simply click on accident and it then opens the URL. If you are seeing the URL open when clicking and dragging your cursor over a URL to select, that is a bug, which I cannot reproduce on my machine.

**Comment by joeky888** [comment]
> you simply click on accident

Yeah, that's not a bug.

> Fixed in #2059.

Thanks.

**Comment by LamaRaz** [comment]
latest stable

Nothing I try seems to disable the url launcher.

echo http://www.google.com

always creates a link and opens firefox when clicked. i want it be text and open nothing

**Comment by joeky888** [comment]
With the version 0.8.0 the `url.launcher` is deprecated, to disable xdg launcher in version 0.8.0:

```yaml
hints:
  enabled:
   - regex: "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)\
             [^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
     command: xdg-open
     post_processing: true
     mouse:
       enabled: false # 👈
       mods: None
```

**Comment by alexzanderr** [comment]
> With the version 0.8.0 the `url.launcher` is deprecated, to disable xdg launcher in version 0.8.0:
> 
> ```yaml
> hints:
>   enabled:
>    - regex: "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)\
>              [^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
>      command: xdg-open
>      post_processing: true
>      mouse:
>        enabled: false # 👈
>        mods: None
> ```

its working. 
when you hover with the mouse on `git:(master)`, for example, its not a URL anymore. 
yay. thanks man.

**Comment by chrisduerr** [comment]
Fyi mouse is disabled by default for hints. So you can just remove the entire `mouse` section.

**Comment by Hubro** [comment]
For my fellow Googlers, you can actually have it both ways.

I don't like that URLs open when I double-click them, because that makes them annoying to select for copying. However, I also often want to open URLs in my default browser, so it would be nice to be able to do that as well.

This configuration enables ctrl+click on links to open them using xdg-open:

```
hints:
  enabled:
    - regex: "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)\
              [^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
      command: xdg-open
      post_processing: true
      mouse:
        enabled: true
        mods: Control
```

And I can now double-click to select.

**Comment by alexzanderr** [comment]
i can say you are a pro googler

**Comment by bluesuncat** [comment]
The solutions in this report seem to work for regular links but not for all cases.

When I get certain errors in gcc, there are often hyperlinks included.

Running a hello world without stdio.h will result in:

`warning: implicit declaration of function ‘printf’ [-Wimplicit-function-declaration]`
where -Wimplicit-function-declaration will be a hyperlink to gcc.gnu.org

No matter how I configure alacritty, it seems impossible to disable the link feature and a single click on the error message will open a browser.

How do I disable ALL hyperlinks in alacritty?

**Comment by kchibisov** [comment]
You set the `hyperlinks: false` for the default regex hint?

**Comment by bluesuncat** [comment]
> You set the hyperlinks: false for the default regex hint?

This seems to be ignored no matter how I set it. 

Here is the config:

```
hints:
  hyperlinks: false

enabled:
   - regex: "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)\
             [^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
     hyperlinks: false
     command: false
     post_processing: true
     mouse:
       enabled: false
       mods: Control
     binding:
       key: U
       mods: Control|Shift
```

It still executes xdg-open when a link is clicked on.
