### ISSUE TITLE
Custom URL Launcher

### ISSUE THREAD

**Issue by sabrehagen** [jwilm/alacritty#2112]
When opening URLs with Alacritty, I want to supply my own launcher program with prepared arguments ready for Alacritty to append the clicked url on the end.

Is the following syntax supported? I would be using this to launch a browser inside a container. X11 Ubuntu 18.04.

```
  url:
    launcher: 
      program: /jackson/home/repositories/sabrehagen/desktop-environment/scripts/exec.sh
      args:
        - google-chrome
```

**Comment by nixpulvis** [comment]
Though not documented in the config file, it is supported. I've just tested it with this config entry and it seems to be working as expected.

```yml
mouse:
  url:
    launcher:
      program: firefox
      args:
        - --new-window
```

**Comment by kevr** [comment]
This is outdated.

`[2021-11-15 13:50:25.691992634] [WARN ] [alacritty_config_derive] Config warning: url is deprecated; use `hints` section instead`

But I'm not really able to easily find docu about using hints to control the URL launcher.

Any tips?

**Comment by nitnelave** [comment]
For the record, the relevant section in the docs is the one about regex hints:
 - First match the text with a regex (e.g. "it starts with http:// or https://", there are good examples in the alacritty.yml file provided with every release)
 - Then you can specify what program to use, whether you can click on it, what keyboard shortcut to use and so on. It's all in the docs.

You end up with something that looks like (as of this writing):
```yaml
hints:
  enabled:
   - regex: "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:
   ..|news:|file:|git:|ssh:|ftp:)\
             [^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
     command: firefox
     post_processing: true
     mouse:
       enabled: true
       mods: None
     binding:
       key: U
       mods: Control|Shift
```
