### ISSUE TITLE
BUG(?): Forced Fullscreen

### ISSUE THREAD

**Issue by Kreyren** [jwilm/alacritty#2167]
Alacritty on debian buster starts on fullscreen which can't be turned off using `fullscreen: false` in `alacritty.yml`.

OS: Debian Buster
DM: X11 with --scale 2x2
DE: GNOME
aptli: http://ix.io/1D4y
Default config: http://ix.io/1D4x

From https://github.com/jwilm/alacritty/issues/38 i tried to add:
`fullscreen: false` under and above `window` which does not affect it.

Didn't find any instructions to configure alacritty in https://github.com/jwilm/alacritty#configuration

default `alacritty.yml` doesn't have anything related to fullscreen.

Expected to start in windowed mode.

**Comment by chrisduerr** [comment]
When you say 'fullscreen' are you actually talking about fullscreen or a maximized window? I'd assume it overlaps everything?

Does setting the cols and lines in the config work?

**Comment by Kreyren** [comment]
> When you say 'fullscreen' are you actually talking about fullscreen or a maximized window? I'd assume it overlaps everything?
> 
> Does setting the cols and lines in the config work?

mb i though it was fullscreen, but it starts maximalized. updated OP

**Comment by chrisduerr** [comment]
@Kreyren How about the `dimensions` configuration option? Does that do anything for you?

**Comment by Kreyren** [comment]
> @Kreyren How about the `dimensions` configuration option? Does that do anything for you?

is disabled:
```yaml
  # Window dimensions (changes require restart)
  #
  # Specified in number of columns/lines, not pixels.
  # If both are `0`, this setting is ignored.
  dimensions:
    columns: 0
    lines: 0
```

`columns: 1` && `lines: 0` -> same issue
`columns: 0` && `lines: 1` -> same issue
`columns: 1` && `lines: 1` -> same issue
`columns: 10` && `lines: 0` -> same issue
`columns: 0` && `lines: 10` -> same issue
`columns: 10` && `lines: 10` -> same issue
