### ISSUE TITLE
[macOS] Cannot toggle full-screen with `decorations: buttonless`

### ISSUE THREAD

**Issue by erydo** [jwilm/alacritty#2215]
Currently on macOS, when running with the config:
```yml
window:
  decorations: buttonless
```

The lack of buttons and standard menu items make it (seem?) near-impossible to toggle full screen for a window.

As a temporary workaround, I've added to my config:
```yml
key_bindings:
  - key: F
    mods: Command|Shift
    command:
      program: osascript
      args:
        - -l
        - JavaScript
        - -e
        - |
          const fullScreen =
            Application('System Events')
            .processes['Alacritty']
            .windows
            .whose({focused: {'=': true}})[0]
            .attributes['AXFullScreen'];
          fullScreen.value = !fullScreen.value();
```

But that required some tinkering with Automation that I wasn't already been familiar with.

This issue could be made redundant with #2012 (_"Implement Alt + Enter to fullscreen on Windows"_) if it were solved/retitled more generally like _"Expose ToggleFullScreen as an Action"_.
