### ISSUE TITLE
Send notification when URL command completes successfully.

### ISSUE THREAD

**Issue by sudoforge** [jwilm/alacritty#2249]
It'd be great to have a notification sent when the command used to launch a URL has completed successfully. `notify-send` is one generic way to accomplish this.

**Comment by chrisduerr** [comment]
You can already freely set which command should run once you click on a URL. This also means that there's nothing stopping you from adding `notify-send` to that command to automatically send a notification.

**Comment by sudoforge** [comment]
@chrisduerr Perhaps I'm doing something wrong, but this does **not** seem possible.

**`alacritty.yml`**

```
mouse:
  url:
    launcher:
      program: 'notify-send -t 3000 "testing notification" && qutebrowser'
```

After attempting to click on a URI, the following error is recorded:

```
$ cat /tmp/Alacritty-XXXXX.log
[2019-04-02 17:15] [WARN] Unable to launch notify-send -t 3000 "testing notification" && qutebrowser with args ["http://localhost:37249/1vO"]

**Comment by sudoforge** [comment]
I should note, too, that this occurs with and without the single quotes wrapped around `mouse.url.launcher.program`.

**Comment by chrisduerr** [comment]
> Perhaps I'm doing something wrong

You are. You're specifying a program with arguments. This is not a shell script.

The way a program is specified is thouroughly documented in the keybinding section. But the short version is that if you probably want to specify a script as program since that can handle taking the last argument as URL and will still properly spawn bash through the shebang.

Something like this should work:
```yaml
mouse:
  url:
    launcher:
      program: /path/to/bash/script.sh
```
