### ISSUE TITLE
Mixed font sizes

### ISSUE THREAD

**Issue by apenney** [jwilm/alacritty#2351]
Which operating system does the issue occur on?

Windows 10 (insider preview, so the may 2019 release)

I just installed Windows 10, WSL, and Alacritty 0.3.2.  I'm seeing something weird with fonts, where it looks like some are smaller than others or it's substituting them for something else, it's hard to explain so here's a screenshot:

![alacritty](https://user-images.githubusercontent.com/9492/56544738-52549580-6543-11e9-888f-7cfc577ec977.png)

 hope you can see that "set" and "grep" are small, as is "ls" and "term" in xterm.  It's really weird, I've just set it to Input Mono Condensed, first font I installed.  I tried with conpty and without.  My font config is:

```
font:
  # Normal (roman) font face
  normal:
    # Font family
    #
    # Default:
    #   - (macOS) Menlo
    #   - (Linux) monospace
    #   - (Windows) Consolas
    family: Input Mono Compressed

    # The `style` can be specified to pick a specific face.
    style: Regular
  size: 14.0
```

I tried Operator Mono, same problem with it mixing and matching stuff.  It may be related to the broken unicode characters in my prompt?

I started WSL as just:

```
shell:
  program: "wsl.exe ~"
```

Not sure if that's right and could be contributing to this.
