### ISSUE TITLE
How should I contribute to the wiki pages

### ISSUE THREAD

**Issue by antonholmberg** [jwilm/alacritty#2402]
Hi!

I have made an attempt at making a [night owl](https://github.com/sdras/night-owl-vscode-theme) color theme. I am not familiar with how you want me to contribute that to the wiki. Here is the code for it

```yaml
colors:
  # Default colors
  primary:
    background: '0x011627'
    foreground": '0xd6deeb'

  cursor:
    text: '#FFFFFF'
    cursor: '0x234d70'

  selection:
    background: '0x1b90dd4d'

  normal:
    white: "0xffffff"
    black: "0x011627"
    blue: "0x82AAFF"
    cyan: "0x21c7a8"
    green: "0x22da6e"
    magenta: "0xC792EA"
    red: "0xEF5350"
    yellow: "0xaddb67"

  bright:
    white: "0xffffff"
    black: "0x575656"
    blue: "0x82AAFF"
    cyan: "0x7fdbca"
    green: "0x22da6e"
    magenta: "0xC792EA"
    red: "0xEF5350"
    yellow: "0xffeb95"
```
