### ISSUE TITLE
font fallback option panic on windows10.

### ISSUE THREAD

**Issue by evolighting** [jwilm/alacritty#2485]
Which operating system does the issue occur on?
    -windows10

fallback option cause panic:
"panicked at 'unexpected end of mapping '"

which work:

```
 normal:
   family: simhei
   style: Regular 
```

which panic:

```
 normal:
   - family: Source Code Pro
   - family: Powerline
     options: { size: 12 }

```

**Comment by cole-h** [comment]
Those extraneous dashes (`-`) seem to be your problem. Changing your config to 
```yml
 normal:
   family: Source Code Pro
   family: Powerline
     options: { size: 12 }
```
prevent that from panicking.
