### ISSUE TITLE
shell: /bin/bash --login fails

### ISSUE THREAD

**Issue by minhajuddin** [jwilm/alacritty#252]
To make alacritty use a `login` shell, I used the following config. But it fails with an error

```yaml
mouse_bindings:
  - { mouse: Middle, action: PasteSelection }

shell: /bin/bash --login
```

```
alacritty $ alacritty 
device_pixel_ratio: 1
width: 1918, height: 1078
Initializing glyph cache
got font path="/home/minhajuddin/.local/share/fonts/Sauce Code Powerline Regular.otf"
num fonts = 436
num fonts = 436
Finished initializing glyph cache in 0.02053962
set_inner_size: 724px × 580px
width: 724, height: 580
Cell Size: (9 x 24)
PTY Dimensions: Line(24) x Column(80)
num_cols, num_lines = 213, 44
width: 1918, height: 1078
child finished with error '256'

alacritty $ 
```

As a workaround I am using this wrapper:

```bash
#!/bin/bash

exec /bin/bash --login
```
