### ISSUE TITLE
Unable to use "command" field for a key binding

### ISSUE THREAD

**Issue by rafaelrinaldi** [jwilm/alacritty#2535]
Which operating system does the issue occur on?
macOS Mojave

I'm trying to create a custom key binding that should open my editor with a specific file. This is what I have:

```yaml
key_bindings:
  # Custom
  - {
      key: Comma,
      mods: Command,
      command: { program: "nvim", args: ["/tmp/test.txt"] },
    }
```

When hitting the key binding I get a warning:

>[WARN] Couldn't run command No such file or directory (os error 2)

Both `nvim` and the file passed down through `args` exist:

```sh
~
❯ which nvim
/usr/local/bin/nvim

~
❯ cat /tmp/test.txt
This is a test
```

Am I doing something wrong?

**Comment by chrisduerr** [comment]
Could you try changing the command from `nvim` to `/usr/local/bin/nvim`? I'd assume that it might not be part of your PATH before the shell is started, which is what Alacritty will receive as path.

**Comment by hellerve** [comment]
I can verify that using the complete path makes the error go away (I’m also on Mojave), but I can’t get this to work anyway. Programs that terminate seem to work fine, even if alacritty loses focus:

```yaml
- command:
    args:
    - -a
    - firefox
    program: /usr/bin/open
  key: Return
  mods: Command
```


But vim never shows up anywhere on my system:

```yaml
- command:
    program: /usr/local/bin/vim
  key: Return
  mods: Command
```

Please let me know if you need any output or need me to run any commands to help you!
