### ISSUE TITLE
[v0.3.3] vim no longer honors colors 

### ISSUE THREAD

**Issue by dllud** [jwilm/alacritty#2565]
Hi,

I am using alacritty on Arch Linux with i3 (X11) and I recently upgraded from version `0.3.2` to `0.3.3`.
After this upgrade vim no longer uses the colors that I defined on `alacritty.yml` and reverts to the default terminal colors. The strange thing though, is that all other programs that I tried (htop, grep, ls) do honor the colors on `alacritty.yml`.
I built alacritty from source (latest commit was 4039f720) and the same problem is present there. Downgrading back to `0.3.2` fixes this. It seems that `0.3.3` changed something that interferes with the way that vim handles colors, but affects no other program that I could try.

How it should look (and does look up til `0.3.2`):
![before](https://user-images.githubusercontent.com/1716156/59786281-cfd82000-92be-11e9-95a2-e090fcc76cce.png)

How it looks on `0.3.3`:
![after](https://user-images.githubusercontent.com/1716156/59786286-d49cd400-92be-11e9-8221-76d363976a64.png)

Here's the relevant bit of my `alacritty.yml`:
```yaml
colors:
  primary:
    background: '0x000000'
    foreground: '0xdddddd'
  normal:
    black:   '0x1b1918'
    red:     '0xf22c40'
    green:   '0x5ab738'
    yellow:  '0xd5911a'
    blue:    '0x407ee7'
    magenta: '0x6666ea'
    cyan:    '0x00ad9c'
    white:   '0xf1efee'
  bright:
    black:   '0x766e6b'
    red:     '0xf22c40'
    green:   '0x5ab738'
    yellow:  '0xd5911a'
    blue:    '0x407ee7'
    magenta: '0x6666ea'
    cyan:    '0x00ad9c'
    white:   '0xf1efee'
  indexed_colors: []
```
