### ISSUE TITLE
Text reflow slow with large grids

### ISSUE THREAD

**Issue by tonobo** [jwilm/alacritty#2567]
I'm running i3 on linux and expiring a heavy performance drop when resizing the terminal (i often switch from half size to full screen mode). It only happens after printing a large log file or something else maybe when the buffer gets filled over time. Sometimes it hangs about 30 seconds.

my actual scrolling configuration:

```yaml
scrolling:
  history: 100000
  multiplier: 3
  faux_multiplier: 3
  auto_scroll: true
```

```
i3 version 4.16.1 (2019-01-27) © 2009 Michael Stapelberg and contributors
apt policy xserver-xorg-core | grep Installed => Installed: 2:1.20.4-1
```
