### ISSUE TITLE
Crashes on startup MacOS Mojave

### ISSUE THREAD

**Issue by LOG67** [jwilm/alacritty#2585]
Which operating system does the issue occur on?

MacOS Mojave 10.14.5

What version of Alacritty?

Alacritty-v0.3.3 downloaded from the releases tab. I tested it with some previous versions and they had it as well. 

Behavior:

Alacritty crashes on startup.

Context:
I believe the issue is related to finding the font family because this happens when I set the normal font in my config to something that does not exist (in the example below the correct font name should be "Fira Code"):
```
# Font configuration (changes require restart)
font:
  # Normal (roman) font face
  normal:
    # Font family
    #
    # Default:
    #   - (macOS) Menlo
    #   - (Linux) monospace
    #   - (Windows) Consolas
    family: "FiraCode"
```
Alacritty behaves normally when provided with an existing font family (e.g. "Fira Code"). 

I attached my config file for more information.
[config.txt](https://github.com/jwilm/alacritty/files/3318843/config.txt)
