### ISSUE TITLE
Create the concept of color themes and a easy way to rotate

### ISSUE THREAD

**Issue by robsonpeixoto** [jwilm/alacritty#2602]
Sometimes the dark is more comfortable than a light theme. But sometimes the place is very illuminated to use a dark theme.

But it will break old configs, but is not a rocket science fix the config file.

The idea is create two new config and a new action.

`theme` config with the name of the default theme.
`themes` config with a list of all themes. The `colors` key is exactly the same fo the current `colors` config.
`RotateTheme` a action to rotate between the theme.
 
```yaml
theme: solarized-dark
themes:
  - name: solarized-dark
    colors: ...
  - name: solarized-light
    colors: ...
```

**Comment by chrisduerr** [comment]
Does the following do what you want?

```yml
my-cool-theme: &theme
  primary:
    background: '0xff00ff'
    foreground: '0x000000'

my-uncool-theme:
  primary:
    background: '0x000000'
    foreground: '0xff00ff'

colors: *theme
```

Note that this is a yaml feature, so there's nothing Alacritty needs to do to support this. It should just work.
