### ISSUE TITLE
Can't set font

### ISSUE THREAD

**Issue by karambaq** [jwilm/alacritty#2678]
Which operating system does the issue occur on?
MacOS

I'm trying to set `M+ 1mn` font and gets this error:

```
Couldn't find a font with name M+ 1mn and style Regular
        Please check the font config in your alacritty.yml.
 ```

While this font installed and I can use it in iTerm2 and VSCode

Config:

```
font:
  # Normal (roman) font face
  normal:
    family: M+ 1mn
    # The `style` can be specified to pick a specific face.
    style: Regular
```

I've also tried like that:
```
font:
  # Normal (roman) font face
  normal:
    family: "M+ 1mn"
    # The `style` can be specified to pick a specific face.
    style: Regular
```

**Comment by kchibisov** [comment]
Does the following work? Its seems like your font have style "regular" instead of "Regular" according to docs. (I've only found `M+ 1m` though)
```yml
font:
  # Normal (roman) font face
  normal:
    family: M+ 1mn
    # The `style` can be specified to pick a specific face.
    style: regular
```
However you can write like this, which should be valid
```yml
font:
  normal:
    family: M+ 1mn
```
