### ISSUE TITLE
Italic fails when style contains spaces e.g. "Light Italic"

### ISSUE THREAD

**Issue by lewisthompson** [jwilm/alacritty#2799]
macOS Catalina

With the following font style defined italics work as expected, e.g. `echo -e "\e[3mItalic"` is italic:

```yaml
  italic:
    family: "IBMPlexMono Nerd Font Mono"
    style: Italic
```

When I include spaces in the style italics do not work as expected.  This fails both with & without quotes:

```yaml
  italic:
    family: "IBMPlexMono Nerd Font Mono"
    style: "ExtraLight Italic"
```
