### ISSUE TITLE
Paste ignored with text/plain target on X11

### ISSUE THREAD

**Issue by dshoreman** [jwilm/alacritty#2811]
Following on from #2595, pasting no longer hangs but instead is completely ignored if a target is defined - even when that target is plain text - resulting in no data being pasted. That's fine if the content is an image for example, but less convenient for text.

### Affected Version
Alacritty 0.3.3 (a3f56a5f09b431524fb32f662fc1d90b1f638ec9 or newer) on Linux with i3/X11

### Replicating

* Copy with `echo "primary" | xclip -selection primary -t text/plain`
* Use middle mouse to paste in Alacritty
* Copy with `echo "clipboard" | xclip -selection clipboard -t text/plain`
* Use `ctrl+shift+v` to paste in Alacritty

Note that using `xclip -o` to paste directly will always work, with or without `-target` passed.

#### Relevant Config
```yaml
mouse_bindings:
  - { mouse: Middle, action: PasteSelection }
key_bindings:
  - { key: Paste, action: Paste }
```
