### ISSUE TITLE
Couldn't find a font with name and style, but fc-match can

### ISSUE THREAD

**Issue by OJFord** [jwilm/alacritty#2812]
Darwin 18.7.0 (macOS 10.14.6)
alacritty 0.3.3 (cc3e4d3)

```
[2019-09-20 13:50] [ERROR] Alacritty encountered an unrecoverable error:

	Couldn't find a font with name Iosevka Myosevka Term and style slant=Normal, weight=Normal
	Please check the font config in your alacritty.yml.

$ fc-match 'Iosevka Myosevka Term:style slant=Normal, weight=Normal'                                    1
myosevka-term-regular.ttf: "Iosevka Myosevka Term" "Regular"
```

It's not a funky whitespace error or similar, I copy-pasted between the error, `fc-match`, and `alacritty.yml` to be sure.

**Comment by kchibisov** [comment]
Style is for `Regular`/`Bold`/`Italic` and so on. We're not providing an option to set slant/weight etc.

**Comment by OJFord** [comment]
@kchibisov That error is from me setting `family` only, no `style`. Sorry, should have shown the conf snippet.

That's the error when I remove the `style: Regular` (and `Medium` and `Light`) that I was using, with those it's the same error but with those styles, and `fc-match` can still find them.

**Comment by kchibisov** [comment]
So your config is something like
```yaml
font:
  normal:
    family: Iosevka Myosevka Term
```
right?

**Comment by OJFord** [comment]
```
font:
  normal:
    family: Iosevka Myosevka Term
  bold:
    family: Iosevka Myosevka Term
  italic:
    family: Iosevka Myosevka Term
```

and have also tried with `style:`s.

**Comment by kchibisov** [comment]
Do you have this font in macOS font book app? You should use the name from it btw.

**Comment by OJFord** [comment]
> You should use the name from [macOS font book app] btw.

OK, that was it.

For some reason Font Book.app is giving it a different name (that I think it used to have, so presumably there's some caching go on) and ignoring the current actual family name that `fc-match` uses.

I can workaround that by using `/Libary/Fonts` instead of my user fonts, which isn't ideal of course but maybe it'll go away on reboot 🤷‍♂  (and of course it's a macOS issue anyway).

However, though it does now startup without error, all characters are rendered as 'question mark in box'. In the Font Book preview it looks fine. Any idea what causes that? I tried with & without hinting, unsure if perhaps it wasn't supported, but same result.

**Comment by kchibisov** [comment]
box with question means, that glyph isn't presented in a font, maybe you need to install your font the way macOS wants it (by double click on it and pressing install button). I'm not sure that fc-match and other tools are relevant on macOS, since it's a fontconfig thing, isn't it?.

**Comment by OJFord** [comment]
Nope, whether or not I add from Font Book or just drop into the dir it appears correctly in the app:
<img width="439" alt="Screen Shot 2019-09-20 at 15 43 20" src="https://user-images.githubusercontent.com/3946014/65336029-77fecd00-dbbd-11e9-9193-25ef2e164a65.png">

but not in alacritty.

In Firefox however on this page if I change the CSS to `font-family: 'Iosevka Myosevka Term'` it picks it up and renders correctly.

**Comment by kchibisov** [comment]
would you mind trying to set style to Light explicitly?

**Comment by OJFord** [comment]
I am presently using:
```
font:
  normal:
    family: Iosevka Myosevka Term
    style: Light
  bold:
    family: Iosevka Myosevka Term
    style: Medium
  italic:
    family: Iosevka Myosevka Term
    style: Light Italic
```

(but had the same results without `style` lines.)
