### ISSUE TITLE
Tmux austostart?

### ISSUE THREAD

**Issue by pentago** [jwilm/alacritty#2956]
Which operating system does the issue occur on?
MacOS Catalina

I understood that if I set default shell to say a zsh and pass argument like "-c tmux attach || tmux" that Alacritty will attach tmux session if it exists and if not, start a new one but having that argument in .yml config just makes the terminal not starting at all.

Did I misunderstand how it works and what's the best way to achieve this behavior?
iTerm allows setting similar command and works as expected but I'd like to continue using Alacritty as it looks and works better for me.

Thanks in advance!

**Comment by kchibisov** [comment]
It should be like this:

```yml
shell:
  program: /bin/bash
  args:
    - -c
    - "tmux attach || tmux"
```

**Comment by pentago** [comment]
Yep, that's pretty much it. Thanks a ton!

**Comment by alex-popov-tech** [comment]
@kchibisov hello! if I use snipped provided by you, icons seems not to be rendered:

config:
```
shell:
  program: /bin/zsh
  args:
    - -l
    - -c
    - "tmux"

font:
  normal:
    family: "JetBrainsMono Nerd Font"
  size: 16
  glyph_offset:
    y: 1
  use_thin_strokes: true
```

manual - https://share.getcloudapp.com/L1ugv562
auto - https://share.getcloudapp.com/GGuN5X5X

any ideas why that could happen?

**Comment by kchibisov** [comment]
This is a locale issue.

**Comment by kchibisov** [comment]
Note, if you're manually setting locale somewhere in a shell, you shouldn't do it there, you should set locale in `alacritty.yml` in `env` section.

**Comment by alex-popov-tech** [comment]
i did set locale in zsh_env file, after moving it to env:
```
env:
  LC_ALL: en_US.UTF-8
  LANG: en_US.UTF-8
```
it works as expected, thanks! @kchibisov

**Comment by alex-popov-tech** [comment]
@kchibisov sorry for bothering, but in context of tmux autostart - this is a common practice to have tmux attach/create as a single command, f.e. `tmux attach -t '(∩Ȍ▾Ȍ)⊃━☆ﾟ,*' || tmux new -s '(∩Ȍ▾Ȍ)⊃━☆ﾟ,*'` - how can I use that in alacritty? It fails now on 
```
program: tmux
args: 
  - ...
  - ||
```

**Comment by kchibisov** [comment]
https://github.com/alacritty/alacritty/issues/2956#issuecomment-549505530

**Comment by alex-popov-tech** [comment]
sorry, my bad, works now...thanks !

**Comment by yashank09** [comment]
> @kchibisov hello! if I use snipped provided by you, icons seems not to be rendered:
> 
> config:
> 
> ```
> shell:
>   program: /bin/zsh
>   args:
>     - -l
>     - -c
>     - "tmux"
> 
> font:
>   normal:
>     family: "JetBrainsMono Nerd Font"
>   size: 16
>   glyph_offset:
>     y: 1
>   use_thin_strokes: true
> ```
> 
> manual - https://share.getcloudapp.com/L1ugv562
> auto - https://share.getcloudapp.com/GGuN5X5X
> 
> any ideas why that could happen?

could be due to difference in color schema. Use this setting had you'll be good :) 
set -g default-terminal "screen-256color"

**Comment by i11v** [comment]
@alex-popov-tech 

> this is a common practice to have tmux attach/create as a single command, f.e. `tmux attach -t '(∩Ȍ▾Ȍ)⊃━☆ﾟ,*' || tmux new -s '(∩Ȍ▾Ȍ)⊃━☆ﾟ,*'` - how can I use that in alacritty? It fails now on
> 
> ```
> program: tmux
> args: 
>   - ...
>   - ||
> ```

You can use simplify the command even more using the `-A` flag like this: `tmux new -A -s '(∩Ȍ▾Ȍ)⊃━☆ﾟ,*'`.
Here is its description from tmux man:
```
             The -A flag makes new-session behave like attach-session if
             session-name already exists; in this case, -D behaves like
             -d to attach-session, and -X behaves like -x to
             attach-session.
```

As of the issue topic, the following config works for me:
```yaml
shell:
  program: /usr/local/bin/tmux
  args:
   - new
   - -A
   - -s main
```

**Comment by reportaman** [comment]
@i11v With that config, alacritty flashes and exits immediately.

**Comment by pentago** [comment]
This works fine:

```
shell:
  program: zsh
  args:
    - -l
    - -c
    - "tmux attach || tmux new -s main"
```

**Comment by reportaman** [comment]
Is it possible to kill tmux server, but go back to terminal's main shell without losing the window?

**Comment by reportaman** [comment]
The popular answer from @kchibisov does not source bashrc, that won't work in case you have some tmux keybindings run scripts that work only if bashrc were sourced. I use zsh so the answer below is with zsh. Replace zsh with bash if you use bashrc

```
shell:
  program: /bin/zsh
  args:
    - -l
    - -c 
    - "source ~/.zshrc; tmux attach 2> /dev/null || tmux"
```

**Comment by ngryman** [comment]
@kchibisov's solution is how this should be done. However, for some reason, Alacritty flashes and exits for me.

There's another alternative that I'd like to share. We can tell `tmux` to create a session by default when the server starts and attach to it.

This can be done with one line in the `.tmux.conf` file:
```conf
new-session -s main
```

In `alacritty.yml`, you then can simply run `tmux attach`:
```yml
shell:
  program: /usr/local/bin/tmux
  args:
    - attach
```

**Comment by blueray453** [comment]
Fish Shell

```
shell:
 program: /usr/bin/fish
 args:
   - -c
   - "tmux attach || tmux"
```
