### ISSUE TITLE
Keybindings Configurable from File

### ISSUE THREAD

**Issue by jwilm** [jwilm/alacritty#3]
Keybindings are currently hardcoded in `src/input.rs`. Instead, they should all be specified in the `alacritty.yml` file. Currently hardcoded keybindings should be added to the default `alacritty.yml` config.

There's a couple of binding types we need to support
1. Given a key combination and terminal state, send an escape sequence.
2. Given a key combination and terminal state, perform a predefined action
   - Actions: `copy-selection`, `paste`, `toggle-fullscreen`

I imagine the config might look something like this

``` yml
bindings:
  - key: f11
    escape: [23~
  - key: enter
    mods: super # super and cmd are interchangeable modifiers
    action: full-screen
  - mouse: 5
    action: paste
  - key: left arrow
    mode: app-cursor
    escape: OD
```

Notes on the above config:
- `mods` defaults to no mods
- `mode` defaults to any mode
- keys like `left arrow` would be easy to screw up the identifier for. Better option there?
- full-screen isn't current supported
- clipboard stuff isn't currently supported

One thing that's nice about the current approach is bindings for each key are available in a static location. It would be nice to still be able to jump to the binding list for a given key using an array or Vec or `match` instead of going through a HashMap.

I think the initial implementation of this will be supporting the current keybindings but defined from the config file instead of hard-coded.
