### ISSUE TITLE
Bound keys are sometimes executed for the wrong window after focus change

### ISSUE THREAD

**Issue by murdegern** [jwilm/alacritty#3175]
Hello,

the bug is best described by how to reproduce it:
- open two alacritty windows
- focus the first window, type something (not using  bound keys)
- focus the second window
- type a bound key

Result: the action of the bound key is executed in the first window
Expected result: the action of the bound key should be executed in the second window

If you type a single unbound key after focusing the 2nd window before using a bound key, it works as expected.

### System

OS: Linux
Version: 0.4.0
X11, i3 window manager

Thanks and regards,
Torsten

**Comment by chrisduerr** [comment]
I don't think I can reproduce this and it sounds very strange. Is the focus correctly tracked, so does Alacritty's box cursor show up in the Window as soon as it's unfocused?

> If you type a single unbound key after focusing the 2nd window before using a bound key, it works as expected.

Can you provide a little more info on what bindings you're running? If I have a binding on ctrl+shift+v for example would you be able to reproduce with this or does `ctrl` already count as a 'single unbound key'? So just a key binding bound to a single key like `A` would work?

**Comment by nixpulvis** [comment]
I'm also running X11/i3 and I'm unable to reproduce. If you launch Alacritty with `alacritty --print-events | grep Focused` maybe that'll show something useful too?

**Comment by murdegern** [comment]
Okay, I looked a bit more closely now. You're right, it only happens in one special case I use - sorry for that.

The one problem I have appears with these bindings:
```yaml
key_bindings:
  - { key: Right,    mods: Alt,   command: { program: tmux, args: [ next-window ] } }
  - { key: Left,     mods: Alt,   command: { program: tmux, args: [ previous-window ] } }
  - key: A
    mods: Alt|Control
    chars: "# you just pressed Alt + Control + A.\x0d"
  - key:  U
    mods: Alt|Control
    action: IncreaseFontSize
```
Control+Alt+A and Control+Alt+U work perfectly. Only the tmux calls work on the unfocused window.
