### ISSUE TITLE
Default config file should work for macOS and Linux

### ISSUE THREAD

**Issue by jwilm** [jwilm/alacritty#40]

**Comment by jwilm** [comment]
Would need a way to support `monospace` as a font family on macOS. I'm not sure of a good way to do that.

**Comment by durka** [comment]
How about an array of font fallback options?

```yaml
font:
  - &a
    family: monospace
    # optional keys: style, bold.family, bold.style, italic.family, italic.style
    size: 11.0
    offset: { x: 2.0, y: -7.0 }
  -
    <<: *a # pulls in any un-repeated keys (e.g. size) from above
    family: Menlo
    offset: { x: 1.0, y: -1.0 }
```
