### ISSUE TITLE
Add config for window starting position

### ISSUE THREAD

**Issue by Valloric** [jwilm/alacritty#41]
Gnome terminal and others support specifying a starting geometry for the screen, usually in terms of chars. So "200x50" is 200 vertical chars and 50 horizontal ones. That plus a pixel offset from top-left of screen lets the user decide how big should the alacritty window be and where should it be placed. With this in config, the window is always where I want it.

Something like this:

```yaml
window:
  vertical_chars: 50
  horizontal_chars: 100
  starting_x_offset: 100
  starting_y_offset: 100
```

You could put the `fullscreen` property (from #38) on the same `window` block too.
