### ISSUE TITLE
Operator Mono and VIM

### ISSUE THREAD

**Issue by asilvadesigns** [jwilm/alacritty#489]
## Update: Solved
See below.

Trying to figure out how to render italics properly using operator mono and vim. Book Italic is the correct weight, if I set it as the normal font face, it renders perfectly but using it as the italic, and in combination with the Vimrc settings is no good. Any insights?

In alacritty config:
```
font:
  normal:
    family: OperatorMonoSSm
    style: Book

 italic:
    family: OperatorMonoSSm
    style: Book Italic

```

In my vimrc.
```
highlight Comment gui=italic cterm=italic
highlight htmlArg gui=italic cterm=italic
```
