### ISSUE TITLE
Grays don't seem to show up properly

### ISSUE THREAD

**Issue by brandur** [jwilm/alacritty#503]
I've noticed while using Alacritty that programs that make use of gray colors don't seem to work properly. Here's Alacritty:

<img width="557" alt="screenshot 2017-04-02 09 12 52" src="https://cloud.githubusercontent.com/assets/96890/24588836/0507e31c-1785-11e7-88ee-dd47fdbf8717.png">

(Note the nearly invisible "reply arrows" close to the right side of the screen.)

And here's iTerm2 for comparison:

<img width="632" alt="screenshot 2017-04-02 09 12 59" src="https://cloud.githubusercontent.com/assets/96890/24588839/1470fbc2-1785-11e7-9346-7c61ea7a7189.png">

I assume that these are the `Gray` and `Darkgray` codes, but I haven't confirmed yet. And while these appear to be widespread colors, I guess maybe they're not in the original set of ANSI escape codes? (And thus don't appear in Alacritty's source.) I don't have a good understanding of this, but I figured I'd open an issue while investigating in case it's obvious to someone else.

**Comment by boxofrox** [comment]
Have you tried changing the colors in `alacritty.yml`\[[1]]?  The defaults there may not be ideal.

[1]: https://github.com/jwilm/alacritty#configuration
\[[1]]: https://github.com/jwilm/alacritty#configuration

**Comment by brandur** [comment]
> Have you tried changing the colors in alacritty.yml[1]? The defaults there may not be ideal.

Ah yes, I know about configuration and took a look at the implementation in `ansi.rs`. I suspect that the problem here is that `Gray` and `Darkgray` are not supported, but I'm not 100% sure about that. More digging is definitely required.

Here are Alacritty's supported colors:

``` yaml
  # Normal colors
  normal:
    black:   '0x000000'
    red:     '0xd54e53'
    green:   '0xb9ca4a'
    yellow:  '0xe6c547'
    blue:    '0x7aa6da'
    magenta: '0xc397d8'
    cyan:    '0x70c0ba'
    white:   '0x424242'
```
