### ISSUE TITLE
PSA: FreeType font metrics fix + config changes

### ISSUE THREAD

**Issue by jwilm** [jwilm/alacritty#533]
We recently landed #317 which, among other things, fixed how we are using FreeType's font metrics. There's no longer a need for wacky font offsets. Unfortunately, many people currently have extreme offsets in their config because of the original implementation.

This PSA is to reduce the surprise at font offsets looking very different after building the latest master. The fix is to restore offsets to `x: 0, y: 0` and make any adjustments needed from there. Additionally, there's a new parameter `glyph_offset` which changes the position of glyphs within cells instead of changing the size of the cells. Here's an excerpt from the default config:

```yaml
  # Glyph offset determines the locations of the glyphs within their cells with
  # the default being at the bottom. Increase the x offset to move the glyph to
  # the right, increase the y offset to move the glyph upward.
  glyph_offset:
    x: 0.0
    y: 0.0
```

If anyone has a suggestion on how to release changes like this in the future with lower friction, please comment here.
