### ISSUE TITLE
Problem loading fonts

### ISSUE THREAD

**Issue by pipriles** [jwilm/alacritty#582]
Hello, I am trying to use this font: [ypn envypn](https://ywstd.fr/p/pj/#envypn)

My configuration looks like this:

```yml
font:
  normal:
    family: ypn envypn 
  bold:
    family: ypn envypn 
  italic:
    family: ypn envypn 
  size: 9.0
  offset:
    x: 0.0
    y: 0.0
  use_thin_strokes: false
```

But i get the following error:

```bash
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', src/libcollections/vec.rs:1431
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

Did i miss something? I tried to adjust the size and the offset to see if there would be any difference but it's the same, is this a bug?
