### ISSUE TITLE
"Invalid pixel size" when using xos4 Terminus font

### ISSUE THREAD

**Issue by osa1** [jwilm/alacritty#619]
I'm using the default config with only this change:

```yaml
font:
  # The normal (roman) font face to use.
  normal:
    family: xos4 Terminus
```

When I run alacritty with this change I get:

```
Alacritty encountered an unrecoverable error:

        Invalid pixel size

```

I tried different pixel sizes but got the same error every time.
