### ISSUE TITLE
Cursor color somehow set to background color in vim

### ISSUE THREAD

**Issue by davidnorthetal** [jwilm/alacritty#704]
At least in vim while using alacritty the cursor behaves weirdly, inverting the fore- background colors instead of setting the bg to "white" and the fg to "black" as is behavior on other TEs.

![cursorcolors](https://user-images.githubusercontent.com/24317742/28817778-8dc22e5a-76a9-11e7-882b-e1ec454c71a5.png)

Haven't seen this in other terminal-emulators and it breaks usability on parens for some reason ( w/ the cursor ending up as the same bg as the term itself ).

Can someone give me pointers what the cause of this is? - I assume this is more then just a misconfiguration, as I don't experience it in any other TEs.

Thanks for any responses.

**Comment by asilvadesigns** [comment]
This os default behaviour for cursor in alacritty, you can change the colors in alacritty.yml if I'm not mistaken.

**Comment by dm1try** [comment]
^ with `custom_cursor_colors` set to `true`
```
  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x000000'
    cursor: '0xffffff'
```
