### ISSUE TITLE
Change color scheme on the fly

### ISSUE THREAD

**Issue by russelldavies** [jwilm/alacritty#749]
I like to switch between a light and dark color profile depending on the time of day. In my config file I have defined the different color schemes and then select which one I desire in the `colors` key like so:
```yaml
color_schemes:
  light: &light
    primary:
      ...
    cursor:
      ...
    ...
  dark: &dark
    ...  

colors: *dark
```
When I want to change the color scheme I just run a shell function which, using sed, replaces the `colors` key with whatever I specify, e.g. `terminal-scheme light`. As the config file is watched, any changes to it are reread and loaded. So this worked well until PR #662 was merged as new config values do not overwrite existing values when reloading.

So what is the best way now to switch between color schemes? Defining the color profiles as escape color codes seems a bit tedious.
